# Generated by Django 5.0.4 on 2024-04-05 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_trialmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 5, 17, 54, 49, 943756)),
        ),
    ]
