# Generated by Django 5.0.4 on 2024-04-05 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_remove_studentprofiles_available_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofiles',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 5, 18, 9, 20, 724219)),
        ),
        migrations.AlterField(
            model_name='trialmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 5, 18, 9, 20, 724219)),
        ),
    ]
