# Generated by Django 5.0.4 on 2024-04-05 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0005_alter_studentprofiles_date_alter_trialmodel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofiles',
            name='academics',
        ),
        migrations.RemoveField(
            model_name='studentprofiles',
            name='goals',
        ),
        migrations.AlterField(
            model_name='studentprofiles',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 5, 18, 25, 59, 200737)),
        ),
        migrations.AlterField(
            model_name='trialmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 5, 18, 25, 59, 200737)),
        ),
    ]
