# Generated by Django 5.0.4 on 2024-04-05 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPerformance',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('html', models.IntegerField(default=0)),
                ('python', models.IntegerField(default=0)),
                ('java', models.IntegerField(default=0)),
                ('dsa', models.IntegerField(default=0)),
                ('oops', models.IntegerField(default=0)),
                ('maths', models.IntegerField(default=0)),
                ('communication', models.IntegerField(default=0)),
                ('writing', models.IntegerField(default=0)),
                ('reading', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGoals',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('domain', models.TextField(default='No Domain')),
                ('duration_weeks', models.IntegerField(default=1)),
                ('available_hours', models.IntegerField(default=24)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfiles',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('uname', models.TextField(default='No Name')),
                ('password', models.TextField(default='No Password')),
                ('domain', models.TextField(default='No Domain')),
                ('duration_weeks', models.IntegerField(default=1)),
                ('available_hours', models.IntegerField(default=24)),
                ('academics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.academicperformance')),
                ('goals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.studentgoals')),
            ],
        ),
    ]
