# Generated by Django 5.0.4 on 2024-04-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialModel',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('uname', models.TextField(default='No Name')),
                ('password', models.TextField(default='No Password')),
            ],
        ),
    ]
