# Generated by Django 5.0.4 on 2024-04-05 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_trialmodel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofiles',
            name='available_hours',
        ),
        migrations.RemoveField(
            model_name='studentprofiles',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='studentprofiles',
            name='duration_weeks',
        ),
        migrations.AddField(
            model_name='academicperformance',
            name='c',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofiles',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 5, 18, 6, 23, 529873)),
        ),
        migrations.AlterField(
            model_name='trialmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 5, 18, 6, 23, 529873)),
        ),
    ]
