# Generated by Django 5.0.4 on 2024-04-05 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0006_remove_studentprofiles_academics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofiles',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 3, 45, 3, 535843)),
        ),
        migrations.AlterField(
            model_name='trialmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 3, 45, 3, 535843)),
        ),
    ]
