# Generated by Django 5.0.4 on 2024-04-06 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0007_alter_studentprofiles_date_alter_trialmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofiles',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 9, 50, 16, 136001)),
        ),
        migrations.AlterField(
            model_name='trialmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 9, 50, 16, 136001)),
        ),
    ]
